services:
  db:
    image: postgres:15
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_DB: wallet_track
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9
    container_name: wallet_flyway
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/wallet_track -user=wallet_user -password=wallet_pass migrate
    volumes:
      - ./db/migrations:/flyway/sql
volumes:
  postgres_data:
