name: Docker Cache

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
    docker-backend-caching:
        permissions:
          packages: write
          security-events: write
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Set lowercase repo owner
            run: |
              echo "REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          - name: Login into GHCR
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner}}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and Push docker image
            uses: docker/build-push-action@v6
            with:
              context: backend
              push: true
              platforms: linux/amd64,linux/arm64 
              tags: ghcr.io/${{ env.REPO_OWNER }}/wallettrack/backend:cache
              cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/wallettrack/backend:cache
              cache-to: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/wallettrack/backend:cache,mode=max

    docker:
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: frontend
        permissions:
            packages: write
            security-events: write
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Set lowercase repo owner
            run: echo "REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          - name: Login into GHCR
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner}}
                password: ${{ secrets.GITHUB_TOKEN }}
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and Push docker image
            uses: docker/build-push-action@v6
            with:
                context: frontend
                push: true
                platforms: linux/amd64, linux/arm64
                tags: ghcr.io/${{ env.REPO_OWNER }}/wallettrack/frontend:cache
                cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/wallettrack/frontend:cache
                cache-to: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/wallettrack/frontend:cache,mode=max